---
apiVersion: v1
kind: ConfigMap
metadata:
  name: policies-github-path
  namespace: open-cluster-management
data:
    path: policies
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: policy-subscription
  namespace: open-cluster-management
spec:
  channel: open-cluster-management/policy-channel
  placement:
    local: true
  packageFilter:
    filterRef:
      name: policies-github-path
