apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesJson6902:
- target:
    group: policy.open-cluster-management.io  
    version: v1
    kind: Policy
    name: policy-auth-provider
  path: cluster01-patch.yaml
